DROP TABLE ACTORDIRECTOR;
CREATE TABLE ACTORDIRECTOR
(
 ACTOR_ID INT,
 DIRECTOR_ID INT,
 TIMESTAMP INT,
 PRIMARY KEY (TIMESTAMP)
);
 
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 0);
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 1);
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 2);
INSERT INTO ACTORDIRECTOR VALUES (1, 2, 3);
INSERT INTO ACTORDIRECTOR VALUES (1, 2, 4);
INSERT INTO ACTORDIRECTOR VALUES (2, 1, 5);
INSERT INTO ACTORDIRECTOR VALUES (2, 1, 6);
COMMIT;