DROP TABLE STUDENTS;
CREATE TABLE STUDENTS (
 STUDENT_ID INT,
 STUDENT_NAME VARCHAR(10),
 PRIMARY KEY(STUDENT_ID)
);

DROP TABLE SUBJECTS;
CREATE TABLE SUBJECTS (
 SUBJECT_NAME VARCHAR(20) PRIMARY KEY
);

DROP TABLE EXAMINATIONS;
CREATE TABLE EXAMINATIONS (
 STUDENT_ID INT,
 SUBJECT_NAME VARCHAR(20)
);
 
INSERT INTO STUDENTS VALUES (1, 'Alice');
INSERT INTO STUDENTS VALUES (2, 'Bob');
INSERT INTO STUDENTS VALUES (13, 'John');
INSERT INTO STUDENTS VALUES (6, 'Alex');

INSERT INTO SUBJECTS VALUES ('Math');
INSERT INTO SUBJECTS VALUES ('Physics');
INSERT INTO SUBJECTS VALUES ('Programming');

INSERT INTO EXAMINATIONS VALUES (1, 'Math');
INSERT INTO EXAMINATIONS VALUES (1, 'Physics');
INSERT INTO EXAMINATIONS VALUES (1, 'Programming');
INSERT INTO EXAMINATIONS VALUES (2, 'Programming');
INSERT INTO EXAMINATIONS VALUES (1, 'Physics');
INSERT INTO EXAMINATIONS VALUES (1,  'Math');
INSERT INTO EXAMINATIONS VALUES (13, 'Math');
INSERT INTO EXAMINATIONS VALUES (13, 'Programming');
INSERT INTO EXAMINATIONS VALUES (13, 'Physics');
INSERT INTO EXAMINATIONS VALUES (2, 'Math');
INSERT INTO EXAMINATIONS VALUES (1, 'Math');
COMMIT;