DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (
 EMPLOYEE_ID INT,
 TEAM_ID INT
);
 
INSERT INTO EMPLOYEE VALUES (1, 8);
INSERT INTO EMPLOYEE VALUES (2, 8);
INSERT INTO EMPLOYEE VALUES (3, 8);
INSERT INTO EMPLOYEE VALUES (4, 7);
INSERT INTO EMPLOYEE VALUES (5, 9);
INSERT INTO EMPLOYEE VALUES (6, 9);
COMMIT;