DROP TABLE CINEMA;

CREATE TABLE CINEMA
(
  SEAT_ID INT NOT NULL 
, FREE CHAR(1) 
, CONSTRAINT CINEMA_PK PRIMARY KEY (SEAT_ID)
);

INSERT INTO CINEMA (SEAT_ID,FREE) VALUES (1,'1');
INSERT INTO CINEMA (SEAT_ID,FREE) VALUES (2,'0');
INSERT INTO CINEMA (SEAT_ID,FREE) VALUES (3,'1');
INSERT INTO CINEMA (SEAT_ID,FREE) VALUES (4,'1');
INSERT INTO CINEMA (SEAT_ID,FREE) VALUES (5,'1');

COMMIT;