SELECT STORE_NAME, SUM(SALES) AS "SUM_SALES"
FROM STORE_INFORMATION
GROUP BY STORE_NAME
HAVING SUM(SALES) > 3000;


SELECT S.STORE_NAME
FROM STORE_INFORMATION S;

SELECT G.*, S.*
FROM GEOGRAPHY G, STORE_INFORMATION S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

SELECT G.*, S.*
FROM GEOGRAPHY G INNER JOIN STORE_INFORMATION S
ON  G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

SELECT G.*, S.*
FROM GEOGRAPHY G INNER JOIN STORE_INFORMATION S
USING (G.GEOGRAPHY_ID);

SELECT G.*, S.*
FROM GEOGRAPHY G LEFT JOIN STORE_INFORMATION S
ON  G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.*, S.*
FROM GEOGRAPHY G RIGHT JOIN STORE_INFORMATION S
ON  G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.*, S.*
FROM GEOGRAPHY G FULL JOIN STORE_INFORMATION S
ON  G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


