SELECT STORE_ID, STORE_NAME,SALES  FROM STORE_INFORMATION;

SELECT *  FROM STORE_INFORMATION;

SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

SELECT DISTINCT  STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT *  FROM STORE_INFORMATION
WHERE SALES >= 1500;

SELECT *  FROM STORE_INFORMATION
WHERE SALES >= 1500 AND STORE_DATE = '2018/05/15';


SELECT *  FROM STORE_INFORMATION
WHERE SALES >= 1500 OR STORE_DATE = '2018/03/09';

SELECT *  FROM STORE_INFORMATION
WHERE STORE_DATE > '2018/03/09';


SELECT * FROM  STORE_INFORMATION
WHERE STORE_ID = 1 OR STORE_ID = 2 OR STORE_ID = 3;

-- IN參數個數上限1千個
SELECT * FROM  STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM  STORE_INFORMATION
WHERE STORE_NAME IN ('Boston','San Diego');

SELECT * FROM STORE_INFORMATION
WHERE SALES >= 250 AND SALES <= 700;

-- 兩者之間(適用於抓取資料範圍區間)
SELECT * FROM  STORE_INFORMATION
WHERE SALES BETWEEN 250 AND 700;


SELECT * FROM  STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-01-01' AND '2018-03-31';

-- 精準查詢、模糊查詢
SELECT STORE_NAME FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'Los%';


SELECT STORE_NAME FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%Angeles';

SELECT STORE_NAME FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%Ang%';

SELECT STORE_NAME FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';

-- PS：若要找尋的資料包含萬用字元，就要使用 ESCAPE 關鍵字並指定適當的「跳脫字元」
SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '!%%' ESCAPE '!';


SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE, GEOGRAPHY_ID 
FROM STORE_INFORMATION
-- 1.「且」找出屬於西區的商店
WHERE GEOGRAPHY_ID = '2'
-- 2.「且」營業額大於300(包含300)
AND SALES >= 300
-- 3.「且」商店名稱“L”開頭
AND STORE_NAME LIKE 'L%' 
-- 4.「或」營業日介於2018年3月至4月
OR STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30';


-- 2,4,5
SELECT * 
FROM STORE_INFORMATION
-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
WHERE 
(GEOGRAPHY_ID = '2' AND SALES >= 300)
-- 4.「或」營業日介於2018年3月至4月
-- 3.「且」商店名稱“L”開頭
OR 
(STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30' AND STORE_NAME LIKE 'L%');

-- Step1:3群資料(先各別下三個sql，並且確認每一個sql的結果是不是如預期)
-- Step2:而且每一個獨立的sql裡面只有and
-- Stpe3:合併並且用or串連

-- 2,4,5
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = '2' AND SALES >= 300;

-- 2
SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%' AND STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30';

-- ASC(預設)由小到大
-- DESC由大到小
SELECT * FROM STORE_INFORMATION
ORDER BY SALES ASC;

SELECT * FROM STORE_INFORMATION
ORDER BY SALES DESC, STORE_DATE ASC;

-- 主排序欄位(總分)
-- 次排序欄位(數學)
-- 次次排序欄位(國文)
-- A君 國:60、英:100、數:100  (總分:260) 
-- B君 國:100、英:100、數:60  (總分:260)

SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
ORDER BY SALES;

SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
ORDER BY 3;

SELECT * FROM STORE_INFORMATION;

SELECT SUM(SALES), COUNT(STORE_ID), AVG(SALES), 
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION;

SELECT COUNT(STORE_ID) 
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NOT NULL;

SELECT COUNT(STORE_ID)  
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NULL;


SELECT COUNT(DISTINCT STORE_NAME) FROM STORE_INFORMATION;


