-- SELECT(選出、抓取)欄位
-- FROM(指定來源)資料表
SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION;

-- *星號代表全部欄位
SELECT * FROM STORE_INFORMATION;

-- 理解(優先記得功能效果)，而非死背SQL語法
-- 資料"去除重覆"
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 總共有六筆資料
-- DISTINCT只能放在SQL欄位"最前面"，"只能下一次"
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

-- 'WHERE'有選擇性(條件性)地抓資料
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES > 1500;

SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES >= 1500;

-- AND (和、而且) 資料'愈少'，"嚴謹"
-- OR (或、或者)  資料'愈多',"寬鬆"

-- Sales 高於 $1,000 "或是" Sales 在 $275 "以及" $500 之間
-- 2,4,5,6
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES > 1000  
OR SALES > 275 AND SALES < 500;

-- 查詢字串欄位的資料時，須加'單引號'
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE STORE_NAME = 'Los Angeles';




