
-- 針對"加總後"的各別商店營業額做"條件篩選"
-- 對函數產生的值來設定條件查尋\
-- GROUP BY → Function → HAVING → ORDER BY
SELECT STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME
HAVING SUM(SALES) >= 3000
ORDER BY SUM(SALES) DESC;