-- 子查詢 Sub Query (個數無限制)
SELECT * FROM STORE_INFORMATION
WHERE SALES = 3000;

-- 商店最高的營業額
SELECT MAX(SALES) FROM STORE_INFORMATION;

-- 查詢"最高營業額"的商店資料
SELECT * FROM STORE_INFORMATION
WHERE SALES = (
	SELECT MAX(SALES) FROM STORE_INFORMATION
);

-- 關聯式的子查詢
-- 外查詢
SELECT S.* FROM STORE_INFORMATION S
WHERE GEOGRAPHY_ID IN (
	-- 內查詢
    SELECT GEOGRAPHY_ID FROM GEOGRAPHY G
    WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
);


