-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)
WITH DEP_AVG AS (
	-- 查詢每個部門平均薪資
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) "DEP_AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
),
EMP AS (
	SELECT E.*, D.DEP_AVG_SALARY
    FROM EMPLOYEES E, DEP_AVG D
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.SALARY > D.DEP_AVG_SALARY
)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.SALARY,
	EMP.DEPARTMENT_ID, D.DEPARTMENT_NAME, EMP.DEP_AVG_SALARY
FROM EMP, DEPARTMENTS D
WHERE EMP.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY EMP.DEP_AVG_SALARY DESC, EMP.SALARY DESC;

