-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, DEP.DEP_AVG_SALARY
FROM (
	-- 1.查詢每個部門的平均部門薪資
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) DEP_AVG_SALARY
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
) DEP 
JOIN EMPLOYEES E ON DEP.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- 2.查詢高於平均部門薪資的員工
WHERE E.SALARY > DEP.DEP_AVG_SALARY
ORDER BY DEP.DEP_AVG_SALARY DESC, E.SALARY DESC;

-- 作業:WITH AS.. CTE