-- 每個部門的平均薪資(DEPARTMENT_ID, AVG_DEP_SALARY)
SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) "AVG_DEP_SALARY"
FROM employees E
GROUP BY E.DEPARTMENT_ID;


SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, FLOOR(AVG(E.SALARY)) "AVG_DEP_SALARY"
FROM departments D 
JOIN employees E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG_DEP_SALARY;