-- 每個部門的平均薪資(DEPARTMENT_ID, AVG_DEP_SALARY)
SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) "AVG_DEP_SALARY"
FROM employees E
GROUP BY E.DEPARTMENT_ID;


SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, 
	MIN(E.SALARY), MAX(E.SALARY), COUNT(E.EMPLOYEE_ID),
	FLOOR(AVG(E.SALARY)) "AVG_DEP_SALARY"
FROM departments D 
JOIN employees E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING FLOOR(AVG(E.SALARY)) > 9000
ORDER BY AVG_DEP_SALARY;

SELECT * FROM departments;


-- HR DB 資料查詢
-- 查詢所有部門資訊如下：
-- 1.所在地(國家、洲省、城市)
-- 2.部門(部門編號、部門名稱)
-- 3.部門管理者(員工編號、員工姓名、員工職稱)

-- Step1:找出要查詢的「資料欄」與「資料表」
-- COUNTRY_ID,STATE_PROVINCE,CITY (LOCATIONS)
-- DEPARTMENT_ID,DEPARTMENT_NAME(DEPARTMENTS)
-- EMPLOYEE_ID,FIRST_NAME(EMPLOYEES)
-- JOB_TITLE(JOBS)

-- Step2:透過第一步所找到的資料表,找出資料表與資料表之間的關聯欄位
-- LOCATIONS(LOCATION_ID)DEPARTMENTS
-- DEPARTMENTS(MANAGER_ID,EMPLOYEE_ID)EMPLOYEES
-- EMPLOYEES(JOB_ID)JOBS

-- Step3:經由Step1、Step2所找尋出的(資料欄、資料表、資料表關聯欄位)撰寫SQL
SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID, E.FIRST_NAME, J.JOB_TITLE
FROM DEPARTMENTS D 
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;


SELECT * FROM COUNTRIES;






