-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

-- 1.每個部門的部門平均薪資(部門平均薪資表)
-- 2.每位員工與部門平均薪資表比較(與同部門相比)

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
	D.DEPARTMENT_NAME,
	T_DEP_INFO.DEP_AVG_SALARY
FROM EMPLOYEES E, DEPARTMENTS D, (
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) DEP_AVG_SALARY
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
) T_DEP_INFO
WHERE E.DEPARTMENT_ID = T_DEP_INFO.DEPARTMENT_ID
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY > T_DEP_INFO.DEP_AVG_SALARY
ORDER BY E.DEPARTMENT_ID, E.SALARY DESC;


SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
	D.DEPARTMENT_NAME,
	T_DEP_INFO.DEP_AVG_SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN (
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) DEP_AVG_SALARY
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
) T_DEP_INFO ON E.DEPARTMENT_ID = T_DEP_INFO.DEPARTMENT_ID
WHERE  E.SALARY > T_DEP_INFO.DEP_AVG_SALARY
ORDER BY E.DEPARTMENT_ID, E.SALARY DESC;


-- WITH (Common Table Expressions)
-- 且查詢與查詢之間可以相互使用欄位做關聯式查詢
WITH T_DEP_INFO AS (
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) DEP_AVG_SALARY
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
),
GREATER_AVG_EMP AS (
	SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, T_DEP_INFO.DEP_AVG_SALARY
    FROM EMPLOYEES E, T_DEP_INFO
    WHERE E.DEPARTMENT_ID = T_DEP_INFO.DEPARTMENT_ID
    AND E.SALARY > T_DEP_INFO.DEP_AVG_SALARY
)
SELECT GREATER_AVG_EMP.*, D.DEPARTMENT_NAME
FROM GREATER_AVG_EMP
JOIN DEPARTMENTS D ON GREATER_AVG_EMP.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY DEPARTMENT_ID, SALARY DESC;

