-- HR DB 資料查詢
-- 查詢所有部門資訊如下：
-- 1.所在地(國家、洲省、城市)
-- 2.部門(部門編號、部門名稱)
-- 3.部門管理者(員工編號、員工姓名、員工職稱)

-- Step1:找出資料欄位、所屬資料表
-- COUNTRY_ID,STATE_PROVINCE,CITY (LOCATIONS)
-- DEPARTMENT_ID,DEPARTMENT_NAME (DEPARTMENTS)
-- EMPLOYEE_ID,FIRST_NAME (EMPLOYEES)
-- JOB_TITLE (JOBS)

-- Step2:找資料表與資料表之間相關聯欄位
-- (LOCATIONS) LOCATION_ID (DEPARTMENTS)
-- (DEPARTMENTS) MANAGER_ID,EMPLOYEE_ID  (EMPLOYEES)
-- (EMPLOYEES)  JOB_ID (JOBS)

-- Step3:寫SQL
SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID, E.FIRST_NAME,
    J.JOB_TITLE
FROM LOCATIONS L
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;
