-- SELECT(選取)、FROM(資料來源表格)
SELECT STORE_NAME FROM store_information;

SELECT STORE_ID, STORE_NAME FROM store_information;

SELECT STORE_ID, SALES, STORE_NAME FROM store_information;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT(資料去重覆)
-- 整列資料欄是否重覆為依據
-- 只能下一次而且要在欄位的開頭
SELECT DISTINCT STORE_NAME FROM store_information;
SELECT DISTINCT STORE_ID,  STORE_NAME FROM STORE_INFORMATION;


-- AND且(嚴僅)資料限縮
-- OR或(寬鬆)資料擴展
SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM store_information
WHERE SALES > 250
AND STORE_DATE > '2018-03-01';


SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM store_information
WHERE SALES > 2500 
OR STORE_DATE > '2018-05-01';


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3
OR STORE_ID = 4;


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3,4);


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 700 AND SALES <= 2500;

-- BETWEEN ... AND 則是讓我們可以運用一個範圍 (range) 內 抓出資料庫中的值
SELECT * 
FROM STORE_INFORMATION
WHERE SALES BETWEEN 700 AND 2500;


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%a%';

-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱'L'開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION 
WHERE GEOGRAPHY_ID = 2;








