-- NOT NULL 不允許一個欄位含有 NULL 值
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) NOT NULL
);

-- UNIQUE 欄位中的所有資料都是不一樣的值
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) UNIQUE
);

-- CHECK 限制是保證一個欄位中的所有資料都是符合某些條件
CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
 	GEOGRAPHY_ID NUMERIC (10,0)
);
