SELECT STORE_ID FROM STORE_INFORMATION;

SELECT STORE_ID,STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID,STORE_NAME,SALES FROM STORE_INFORMATION;

SELECT STORE_ID,SALES,STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT 資料去重覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- DISTINCT說明
-- 1.DISTINCT以多欄位整列資料為去重覆的依據
-- 2.DISTINCT語法只能下在欄位的最前面
-- 3.DISTINCT只能下一次
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;
-- SELECT  STORE_ID, DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- WHERE 選擇性地抓資料
SELECT STORE_ID,STORE_NAME,SALES FROM STORE_INFORMATION WHERE SALES >= 1500;
SELECT STORE_ID,STORE_NAME,SALES FROM STORE_INFORMATION WHERE SALES <= 1500;


-- AND且:嚴謹(條件資料限縮)
-- OR或:寬鬆(條件資料擴展)
SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION 
WHERE SALES >= 300 AND STORE_DATE > '2018-03-01';


SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION 
WHERE STORE_ID = 1 OR STORE_ID = 2 OR STORE_ID = 3;

-- 2,4,5,6
SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION 
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);

-- IN:相同欄位不同值查詢
SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION 
WHERE STORE_ID IN (1,3,2);

SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION
WHERE STORE_NAME = 'Boston' OR STORE_NAME = 'Los Angeles';

SELECT STORE_ID,STORE_NAME,SALES,STORE_DATE 
FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Boston','Los Angeles');


SELECT STORE_ID,STORE_NAME,SALES
FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 1500;

-- BETWEEN ... AND ...
-- 運用一個範圍 (range) 內 抓出資料庫中的值
SELECT STORE_ID,STORE_NAME,SALES
FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 1500;


SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01' AND '2018-05-31';


SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';


SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%a%';

/*
1.「且」找出屬於西區的商店
2.「且」營業額大於300(包含300)
3.「且」商店名稱'L'開頭
4.「或」營業日介於2018年3月至4月
*/
SELECT STORE_ID,STORE_NAME,SALES, STORE_DATE,GEOGRAPHY_ID
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2
AND SALES >= 300
AND STORE_NAME LIKE 'L%'
OR STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30';








