-- NOT NULL 不允許一個欄位含有 NULL 值
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) NOT NULL
);

-- PRIMARY KEY 不允欄位唯重複,且不允許NULL
-- UNIQUE 欄位中的所有資料都是不一樣的值,允許NULL
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) UNIQUE
);

-- CHECK 限制是保證一個欄位中的所有資料都是符合某些條件
CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
 	GEOGRAPHY_ID NUMERIC (10,0)
);

-- 外來鍵(Foreign Key)是一個(或數個)指向另外一個表格主鍵的欄位。
-- 外來鍵的目的是確定資料的參考完整性(referential integrity)
CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
 	GEOGRAPHY_ID NUMERIC (10,0),
 	CONSTRAINT CONSTRAINT_GEOGRAPHY_ID FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY (GEOGRAPHY_ID)
);

-- One to One

-- 政府官員州長
CREATE TABLE Gov(
    GID NUMERIC(3) PRIMARY KEY,
    Name VARCHAR(25),
    Address VARCHAR(30),
    TermBegin date,
    TermEnd date
);

-- 州
-- REFERENCES(參照)、CONSTRAINT(限制)、UNIQUE(唯一)
-- UF:唯一外來鍵 UNIQUE Foreign Key
CREATE TABLE State(
    SID NUMERIC(3) PRIMARY KEY,
    StateName VARCHAR(15),
    Population NUMERIC(10),
    SGID NUMERIC(4),
    CONSTRAINT CONSTRAINT_SGID_UNIQUE UNIQUE (SGID),
	CONSTRAINT CONSTRAINT_FK_GOV_GID FOREIGN KEY (SGID) REFERENCES Gov(GID)
);

INSERT INTO Gov (GID, Name, Address, TermBegin, TERMEND) VALUES (110, 'Bob', '123 Any St', '2009-01-01', '2011-12-31');

INSERT INTO State (SID, StateName, Population, SGID) VALUES (111, 'Virginia', 2000000, 110);

SELECT * FROM Gov;

SELECT * FROM STATE;




