-- 針對群組函式處理後的欄位做條件查詢
SELECT STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME
HAVING SUM(SALES) >= 3000;

-- SELECT -> FROM -> WHERE -> GROUP BY -> HAVING -> ORDER BY
SELECT STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
WHERE SALES >= 0
GROUP BY STORE_NAME
HAVING SUM(SALES) >= 3000
ORDER BY SUM(SALES);

-- 欄位別名: alias(別名)
-- 1.AS "雙引號"
-- 2.AS可省略不寫
-- 3."雙引號"可省略不寫(別名不可以有空白)
SELECT STORE_NAME,
	SUM(SALES) SUM_SALES,
    COUNT(STORE_ID) "STORE COUNT", 
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/') AS "營業額群組清單"
FROM STORE_INFORMATION
GROUP BY STORE_NAME
ORDER BY SUM_SALES;
