-- One to One
SELECT * FROM GOV;
SELECT * FROM STATE;

-- Ont to Many
SELECT * FROM VENDOR;
SELECT * FROM INVENTORY;

-- Many to Many
SELECT * FROM CLASS;
SELECT * FROM STUDENT;
SELECT * FROM classstudent_relation;

SELECT * FROM geography;
SELECT * FROM store_information;

-- View
CREATE VIEW REGION_SALES_AVG AS (
	SELECT G.REGION_NAME, FLOOR(IFNULL(AVG(S.SALES),0)) AVG_SALE
	FROM geography G 
	LEFT JOIN store_information S ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
	GROUP BY G.REGION_NAME
	ORDER BY AVG_SALE DESC
);

SELECT * FROM REGION_SALES_AVG;

-- 加一個欄位
ALTER TABLE STORE_INFORMATION ADD NUM_CUSTOMER NUMERIC;

-- 改變欄位名稱
ALTER TABLE STORE_INFORMATION RENAME COLUMN NUM_CUSTOMER TO NUM_OF_CUSTOMER;

-- 改變欄位的資料種類
ALTER TABLE STORE_INFORMATION MODIFY NUM_OF_CUSTOMER VARCHAR(20);

-- 刪去一個欄位
ALTER TABLE STORE_INFORMATION DROP COLUMN NUM_OF_CUSTOMER;





