-- 各別商店的"加總營業額"、"平均營業額"
-- GROUP BY(群組、合併)
-- 非群組的欄位，必須指定合併方式
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID), FLOOR((SALES)),
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 群組清單
-- 查詢GROUP BY合併前的欄位資料結果
-- MySQL GROUP_CONCAT
SELECT STORE_NAME, COUNT(STORE_ID),
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/')
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- Oracle LISTAGG WITHIN GROUP
SELECT STORE_NAME, COUNT(STORE_ID),
  LISTAGG(SALES, '/') WITHIN GROUP (ORDER BY SALES DESC)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 查詢各別商店總合營額大於3000
-- 函數產生的值來設定條件查尋
-- SELECT -> FROM -> WHERE -> GROUP BY -> HAVING
SELECT STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
-- WHERE SUM(SALES) > 300  
GROUP BY STORE_NAME
HAVING SUM(SALES) > 3000;


-- alias(別名)
-- 1.欄位別名("雙引號")
-- 2.AS 語法可省略
-- 3.雙引號可省略(別名中間不能有空白)
SELECT STORE_NAME, COUNT(STORE_ID) AS "STORE_COUNT",
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/') AS "LIST STORE"
FROM STORE_INFORMATION
GROUP BY STORE_NAME;






