SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, SALES, STORE_ID FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT(資料去重覆)
-- 1.DISTINCT(只能下一次)
-- 2.DISTINCT(只能下在欄位的最前面)
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;


SELECT * 
FROM STORE_INFORMATION 
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或者(寬鬆)
SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 300 AND GEOGRAPHY_ID = 2;

SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 300 AND GEOGRAPHY_ID = 2 OR STORE_ID = 1;

-- Sales 高於 $1,000 或是 Sales 在 $500 及 $275 之間
SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 1000 OR (SALES > 275 AND SALES < 500);

SELECT * 
FROM STORE_INFORMATION 
WHERE STORE_ID = 1 
OR STORE_ID = 2
OR STORE_ID = 3
OR STORE_ID = 4;

SELECT * 
FROM STORE_INFORMATION 
WHERE STORE_ID IN (1, 2, 3, 4);

SELECT * FROM STORE_INFORMATION 
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;



SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;


SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-02-01' AND '2018-05-31';

-- 取日期的部份資訊
SELECT STORE_ID, STORE_NAME, STORE_DATE, YEAR(STORE_DATE), MONTH(STORE_DATE)
FROM STORE_INFORMATION
WHERE YEAR(STORE_DATE) = 2018
AND MONTH(STORE_DATE) BETWEEN 2 AND 5;


-- MySQL日期轉換函數：
-- 字串轉日期
SELECT STR_TO_DATE('2018-02', '%Y-%m');

SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE 
BETWEEN STR_TO_DATE('2018-02', '%Y-%m') AND STR_TO_DATE('2018-05', '%Y-%m');


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%os%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '% %';

-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱'L'開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2
AND SALES >= 300
AND STORE_NAME LIKE 'L%'
OR STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30';

-- ASC:小往大 (ascending)預設
-- DESC:由大往小(descending)
SELECT * 
FROM STORE_INFORMATION
ORDER BY SALES ASC;


SELECT * FROM STORE_INFORMATION ORDER BY SALES DESC;

SELECT * FROM STORE_INFORMATION 
ORDER BY SALES DESC, STORE_DATE DESC;

-- SQL Aggregate Functions 聚合函數
SELECT SUM(SALES), COUNT(STORE_ID), AVG(SALES),
	MIN(SALES), MAX(SALES)
FROM STORE_INFORMATION;

-- 查詢資料是NULL(空值)的個數
SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NULL;

-- 查詢資料不是NULL(非空值)的個數
SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NOT NULL;

-- DISTINCT + COUNT = 資料去重覆資料個數
SELECT COUNT(DISTINCT STORE_NAME)
FROM STORE_INFORMATION;

-- 各別商店營業額加總
-- 資料分群
-- 非群組的欄位必須指定"聚合函數"
-- GROUP BY (欄位分群 + 其它非群組的欄位須指定使用函數合併)
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID), AVG(SALES),
	MIN(SALES), MAX(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;


SELECT STORE_ID, STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_ID, STORE_NAME;

-- MySQL
-- 群組資料清單函數(查尋未群組合併前的資料清單)
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/')
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- Oracle甲骨文
-- 群組資料清單函數
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
   LISTAGG(SALES, '/') WITHIN GROUP (ORDER BY SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;


-- MS SQL微軟
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
	STRING_AGG(SALES, '/') WITHIN GROUP (ORDER BY SALES ASC)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;






