-- SELECT(選取、抓取)、FROM(來源表格)
SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- DISTINCT 只能一次
-- DISTINCT 只能放在欄位的最前面
-- DISTINCT 依多個資料欄一整列判斷是否資料重覆
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, STORE_ID, SALES 
FROM STORE_INFORMATION 
WHERE SALES >= 1500;

-- <>、!= 不等於
SELECT STORE_NAME, STORE_ID, SALES 
FROM STORE_INFORMATION
WHERE SALES != 1500;

-- AND且(嚴謹)、OR或(寬鬆)
-- 高於 $1,000 或是 Sales 在 $275 及 $500 之間
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES > 1000
OR SALES > 275 AND SALES < 500;


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID = 2
OR STORE_ID = 3
OR STORE_ID = 4;


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID IN (2,3,4);


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Boston', 'Los Angeles');

SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 250 AND SALES <= 700;

SELECT * 
FROM STORE_INFORMATION
WHERE SALES BETWEEN 250 AND 700;

SELECT * 
FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01 00:00:00' AND '2018-05-31';

SELECT * 
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * 
FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';

-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱"L"開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2;










