-- 各別商店的"加總營業額"、"平均營業額"
-- GROUP BY(群組、合併)
-- 非群組的欄位，必須指定合併方式
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID), FLOOR((SALES)),
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 群組清單
-- 查詢GROUP BY合併前的欄位資料結果
-- MySQL GROUP_CONCAT
SELECT STORE_NAME, COUNT(STORE_ID),
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/')
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- Oracle LISTAGG WITHIN GROUP
SELECT STORE_NAME, COUNT(STORE_ID),
  LISTAGG(SALES, '/') WITHIN GROUP (ORDER BY SALES DESC)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;





