 -- Alias
 -- 欄位別名
 -- 1.AS可省略不寫
 -- 2.別名使用雙引號括起來(雙引號可省略)
 -- 但書:別名不能有空白
 SELECT STORE_NAME, 
	SUM(SALES) 營業額, 
	COUNT(STORE_ID) "COUNT_STORE",
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/') AS "LIST SALES"
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 表格別名
SELECT S.STORE_NAME AS "商店名稱"
FROM STORE_INFORMATION S;

-- 9筆
SELECT * FROM STORE_INFORMATION;

-- 3筆
SELECT * FROM GEOGRAPHY;

-- 27筆
SELECT S.*, G.* 
FROM STORE_INFORMATION S, GEOGRAPHY G
WHERE S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

-- 內部連結
-- INNER JOIN...ON
-- INNER(可省略不寫)
SELECT S.*, G.* 
FROM STORE_INFORMATION S  INNER JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

-- 外部連結
-- LEFT OUTER JOIN
-- OUTER(可省略不寫)
SELECT S.*, G.* 
FROM STORE_INFORMATION S LEFT OUTER JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

SELECT S.*, G.* 
FROM STORE_INFORMATION S LEFT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE G.GEOGRAPHY_ID IS NULL;

SELECT S.*, G.* 
FROM STORE_INFORMATION S RIGHT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

SELECT S.*, G.* 
FROM STORE_INFORMATION S RIGHT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL;


-- MySQL不支援FULL JOIN
SELECT S.*, G.* 
FROM STORE_INFORMATION S FULL JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;


SELECT S.*, G.* 
FROM STORE_INFORMATION S FULL JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL 
OR G.GEOGRAPHY_ID IS NULL;


-- 查詢各區域的營業額總計
-- 資料結果依營業額總計由大到小排序
-- (不論該區域底下是否有所屬商店)
SELECT G.REGION_NAME, IFNULL(SUM(S.SALES), 0) "SUM_SALES"
FROM GEOGRAPHY G LEFT JOIN STORE_INFORMATION S
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
GROUP BY G.REGION_NAME
ORDER BY SUM_SALES DESC;

SELECT * FROM STORE_INFORMATION S;

-- 查詢各區域的商店個數
-- 資料結果依區域的商店個數由大至小排序
-- (依據商店名稱,不包含重覆的商店)
-- (不論該區域底下是否有所屬商店)
SELECT G.REGION_NAME, COUNT(DISTINCT S.STORE_NAME) "COUNT_STORE"
FROM GEOGRAPHY G LEFT JOIN STORE_INFORMATION S
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
GROUP BY G.REGION_NAME
ORDER BY COUNT_STORE DESC;


SELECT CONCAT(STORE_ID, '_', STORE_NAME, '_', SALES) "CONCAT_STORE"
FROM STORE_INFORMATION;


-- Oracle CONCAT只支援兩個參數
-- Oracle字串串間使用 || 符號來串接欄位
SELECT CONCAT(STORE_ID, STORE_NAME) "CONCAT_STORE",
    STORE_ID || '_' || STORE_NAME || '_' || SALES
FROM STORE_INFORMATION;

-- SUBSTR子字串
SELECT STORE_NAME, SUBSTR(STORE_NAME, 3),
	SUBSTR(STORE_NAME, 3, 2)
FROM STORE_INFORMATION;


SELECT STORE_NAME, TRIM(STORE_NAME), RTRIM(STORE_NAME), LTRIM(STORE_NAME)
FROM STORE_INFORMATION;

-- LEADING (起頭), TRAILING (結尾), or BOTH (起頭及結尾)
SELECT STORE_ID, STORE_NAME,
    TRIM(LEADING 'Bos' FROM STORE_NAME),
    TRIM(TRAILING 's' FROM STORE_NAME),
    TRIM(BOTH 'L' FROM STORE_NAME)
FROM STORE_INFORMATION;


SELECT STORE_ID, STORE_NAME, LENGTH(STORE_NAME)
FROM STORE_INFORMATION;

-- CEIL(x)：返回大於或等於x的最大整數值(無條件進位)
-- FLOOR(x)：返回小於或等於x的最小整數值(無條件捨去)
-- 5.ROUND(x ,[y])：返回(四捨五入)
SELECT FLOOR(123.19);
SELECT CEIL(123.1);
SELECT ROUND(123.15, 1);


SELECT STORE_NAME, FLOOR(AVG(SALES))
FROM store_information
GROUP BY STORE_NAME;
