-- 欄位別名
-- 1.AS 可以省略不寫
-- 2.別名須用雙引號包起來
-- 3.雙引號可省略(旦書:不可有空白)
SELECT STORE_NAME, SUM(SALES) AS "總合營業額", 
	COUNT(STORE_ID) AS "COUNT_STORE",
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/') "LIST SALES"
FROM STORE_INFORMATION
GROUP BY STORE_NAME
ORDER BY STORE_NAME;

-- 表格別名
SELECT G.*, S.* 
FROM geography G, store_information S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- 內部連結
-- INNER JOIN ... ON
SELECT G.*, S.* 
FROM geography G INNER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.*, S.* 
FROM geography G JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- 外部連結
-- OUTER JOIN ... ON
-- 所有"區域"皆須全部查尋,不論該區域底下是否有從屬商店
SELECT G.*, S.* 
FROM geography G  LEFT OUTER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- 所有"商店"皆須全部查尋,不論該商店底下是否有所屬區域
SELECT G.*, S.* 
FROM geography G RIGHT JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- MySQL不支援 FULL JOIN
SELECT G.*, S.* 
FROM geography G  FULL OUTER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- LEFT - INNER
SELECT G.*, S.* 
FROM geography G  LEFT OUTER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL;

-- RIGHT - INNER
SELECT G.*, S.* 
FROM geography G  RIGHT OUTER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
WHERE G.GEOGRAPHY_ID IS NULL;

-- FULL - INNER
SELECT G.*, S.* 
FROM geography G  FULL OUTER JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
WHERE G.GEOGRAPHY_ID IS NULL OR S.GEOGRAPHY_ID IS NULL;

-- 查詢各區域的營業額總計
-- 資料結果依營業額總計由大到小排序
-- (不論該區域底下是否有所屬商店)
SELECT G.REGION_NAME, IFNULL(SUM(S.SALES), 0) "REGION_SUM_SALES"
FROM geography G  LEFT JOIN store_information S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
GROUP BY G.REGION_NAME
ORDER BY SUM(S.SALES) DESC;


-- 查詢各區域的商店個數
-- 資料結果依區域的商店個數由大至小排序
-- (依據商店名稱,不包含重覆的商店)
-- (不論該區域底下是否有所屬商店)
SELECT G.REGION_NAME "Region", IFNULL(COUNT(DISTINCT S.STORE_NAME),0) "Number of Stores"
FROM GEOGRAPHY G LEFT OUTER JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
GROUP BY G.REGION_NAME
ORDER BY COUNT(DISTINCT S.STORE_NAME) DESC;

-- 資料欄合併
SELECT CONCAT(STORE_ID, '_', STORE_NAME, '_', SALES)
FROM STORE_INFORMATION;

-- 子字串
-- substring函數是用來抓出一個欄位資料中的其中一部分
SELECT STORE_NAME, SUBSTR(STORE_NAME, 3), SUBSTR(STORE_NAME, 3, 4)
FROM STORE_INFORMATION;


SELECT STORE_NAME, TRIM(STORE_NAME), LTRIM(STORE_NAME), RTRIM(STORE_NAME)
FROM STORE_INFORMATION;



-- TRIM([[位置] [要移除的字串] FROM ] 字串)
-- [位置] 的可能值為 LEADING (起頭), TRAILING (結尾), or BOTH (起頭及結尾)
SELECT STORE_ID, STORE_NAME,
    TRIM(LEADING 'Bos' FROM STORE_NAME),
    TRIM(TRAILING 's' FROM STORE_NAME),
    TRIM(BOTH 'L' FROM STORE_NAME)
FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- 資料新增
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) 
VALUES (10, 'Apple Inc', 6000,'2022-07-26 17:11:35', 3);

-- 資料更新
-- UPDATE "表格名"SET "欄位1" = [新值] WHERE {條件}
UPDATE STORE_INFORMATION SET SALES = 6600 WHERE STORE_ID = 10;

-- 資料刪除
DELETE FROM STORE_INFORMATION WHERE STORE_ID = 10;

