SELECT STORE_NAME FROM STORE_INFORMATION;

select store_id from STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, SALES,STORE_ID FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT(資料去重覆)
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 1.以整列資料為去重覆的依據
-- 2.DISTINCT只能一次
-- 3.DISTINCT只能下在欄位最前面
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;
-- SELECT DISTINCT STORE_ID, DISTINCT STORE_NAME FROM STORE_INFORMATION;









