-- NOT NULL 不允許一個欄位含有 NULL 值
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) NOT NULL
);

-- PRIMARY KEY 不允欄位唯重複,且不允許NULL
-- UNIQUE 欄位中的所有資料都是不一樣的值,允許NULL
CREATE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMERIC(10 , 0 ) PRIMARY KEY,
    REGION_NAME VARCHAR(255) UNIQUE
);

-- CHECK 限制是保證一個欄位中的所有資料都是符合某些條件
CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
 	GEOGRAPHY_ID NUMERIC (10,0)
);

-- 外來鍵(Foreign Key)是一個(或數個)指向另外一個表格主鍵的欄位。
-- 外來鍵的目的是確定資料的參考完整性(referential integrity)
CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
 	GEOGRAPHY_ID NUMERIC (10,0),
 	CONSTRAINT CONSTRAINT_GEOGRAPHY_ID FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY (GEOGRAPHY_ID)
);



