-- SELECT(選取、抓取)、FROM(來源表格)
SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- DISTINCT 只能一次
-- DISTINCT 只能放在欄位的最前面
-- DISTINCT 依多個資料欄一整列判斷是否資料重覆
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;
