SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_NAME, SALES, STORE_ID FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT(資料去重覆)
-- 1.DISTINCT(只能下一次)
-- 2.DISTINCT(只能下在欄位的最前面)
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;


SELECT * 
FROM STORE_INFORMATION 
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或者(寬鬆)
SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 300 AND GEOGRAPHY_ID = 2;

SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 300 AND GEOGRAPHY_ID = 2 OR STORE_ID = 1;

-- Sales 高於 $1,000 或是 Sales 在 $500 及 $275 之間
SELECT * 
FROM STORE_INFORMATION 
WHERE SALES > 1000 OR (SALES > 275 AND SALES < 500);

SELECT * 
FROM STORE_INFORMATION 
WHERE STORE_ID = 1 
OR STORE_ID = 2
OR STORE_ID = 3
OR STORE_ID = 4;

SELECT * 
FROM STORE_INFORMATION 
WHERE STORE_ID IN (1, 2, 3, 4);

SELECT * FROM STORE_INFORMATION 
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;



SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;


SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-02-01' AND '2018-05-31';

-- 取日期的部份資訊
SELECT STORE_ID, STORE_NAME, STORE_DATE, YEAR(STORE_DATE), MONTH(STORE_DATE)
FROM STORE_INFORMATION
WHERE YEAR(STORE_DATE) = 2018
AND MONTH(STORE_DATE) BETWEEN 2 AND 5;


-- MySQL日期轉換函數：
-- 字串轉日期
SELECT STR_TO_DATE('2018-02', '%Y-%m');

SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE 
BETWEEN STR_TO_DATE('2018-02', '%Y-%m') AND STR_TO_DATE('2018-05', '%Y-%m');


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%os%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '% %';

-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱'L'開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2
AND SALES >= 300
AND STORE_NAME LIKE 'L%'
OR STORE_DATE BETWEEN '2018-03-01' AND '2018-04-30';

