-- 找尋全部的商店名稱
-- SELECT 選取、抓出
-- FROM 資料來源
SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT  STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT 去重覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 1.DISTINCT 語法只能放在欄位的最前面
-- 2.DISTINCT 是以SELECT全部欄位來去重覆
-- 3.DISTINCT 只能寫一次
SELECT  DISTINCT STORE_ID,  STORE_NAME FROM STORE_INFORMATION;

-- WHERE 有條件性的抓取資料
SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES >= 700;

-- AND(而且)嚴僅、OR(或)寬鬆
SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);


