-- 找尋全部的商店名稱
-- SELECT 選取、抓出
-- FROM 資料來源
SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT  STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT 去重覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 1.DISTINCT 語法只能放在欄位的最前面
-- 2.DISTINCT 是以SELECT全部欄位來去重覆
-- 3.DISTINCT 只能寫一次
SELECT  DISTINCT STORE_ID,  STORE_NAME FROM STORE_INFORMATION;

-- WHERE 有條件性的抓取資料
SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES >= 700;

-- AND(而且)嚴僅、OR(或)寬鬆
SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;

-- IN 數量不能超過1千個
SELECT * FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME = 'Los Angeles';


SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES > 200 AND SALES <= 700;

-- BETWEEN 查詢區間範圍資料
-- BETWEEN V1 AND V2
SELECT STORE_ID, STORE_NAME, SALES
FROM STORE_INFORMATION
WHERE SALES BETWEEN 200 AND 700;

SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE = '2018-01-07';

SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01' AND '2018-05-31';

-- 精準搜尋 = 等號
-- 模糊搜尋 LIKE
SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'Los%';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%a%';

SELECT * FROM GEOGRAPHY;


SELECT * FROM STORE_INFORMATION
-- 1.「且」找出屬於西區的商店
WHERE GEOGRAPHY_ID = 2
-- 2.「且」營業額大於300(包含300)
AND SALES >= 300
-- 3.「且」商店名稱 "L" 開頭
AND STORE_NAME LIKE 'L%'
-- 4.「或」營業日介於2018年3月至4月
OR STORE_DATE BETWEEN '2018-03-01' AND '2018-4-30';





