 -- Alias
 -- 欄位別名
 -- 1.AS可省略不寫
 -- 2.別名使用雙引號括起來(雙引號可省略)
 -- 但書:別名不能有空白
 SELECT STORE_NAME, 
	SUM(SALES) 營業額, 
	COUNT(STORE_ID) "COUNT_STORE",
	GROUP_CONCAT(SALES ORDER BY SALES DESC SEPARATOR '/') AS "LIST SALES"
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 表格別名
SELECT S.STORE_NAME AS "商店名稱"
FROM STORE_INFORMATION S;

-- 9筆
SELECT * FROM STORE_INFORMATION;

-- 3筆
SELECT * FROM GEOGRAPHY;

-- 27筆
SELECT S.*, G.* 
FROM STORE_INFORMATION S, GEOGRAPHY G
WHERE S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

-- 內部連結
-- INNER JOIN...ON
-- INNER(可省略不寫)
SELECT S.*, G.* 
FROM STORE_INFORMATION S  INNER JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

-- 外部連結
-- LEFT OUTER JOIN
-- OUTER(可省略不寫)
SELECT S.*, G.* 
FROM STORE_INFORMATION S LEFT OUTER JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

SELECT S.*, G.* 
FROM STORE_INFORMATION S LEFT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE G.GEOGRAPHY_ID IS NULL;

SELECT S.*, G.* 
FROM STORE_INFORMATION S RIGHT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;

SELECT S.*, G.* 
FROM STORE_INFORMATION S RIGHT JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL;


-- MySQL不支援FULL JOIN
SELECT S.*, G.* 
FROM STORE_INFORMATION S FULL JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID;


SELECT S.*, G.* 
FROM STORE_INFORMATION S FULL JOIN GEOGRAPHY G
ON S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL 
OR G.GEOGRAPHY_ID IS NULL;




