-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID
FROM employees E
ORDER BY E.DEPARTMENT_ID, E.SALARY DESC;


SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, DEP_AVG_SALARY.AVG_DEP
FROM (
	-- 1.查詢每個部門平均薪資
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(E.SALARY)) "AVG_DEP"
	FROM employees E
	GROUP BY E.DEPARTMENT_ID
) DEP_AVG_SALARY, employees E, departments D
WHERE E.DEPARTMENT_ID = DEP_AVG_SALARY.DEPARTMENT_ID
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- 2.與原先的employees員工做平均薪資比較(大於)
AND E.SALARY > DEP_AVG_SALARY.AVG_DEP
ORDER BY E.DEPARTMENT_ID;

-- 簡單子查詢
-- 查詢與查詢之間彼此獨立不能互相使用對方的欄位
SELECT G.*, S.*
FROM (
   SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
) G , 
(
   SELECT S.GEOGRAPHY_ID, STORE_NAME 
   FROM STORE_INFORMATION S -- , G
   -- WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
) S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- 關聯子查詢
WITH G AS (
	SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
),
S AS (
   SELECT GEOGRAPHY_ID, STORE_NAME FROM STORE_INFORMATION
)
SELECT G.*, S.*
FROM G, S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


WITH G AS (
	SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
),
S AS (
   SELECT S.GEOGRAPHY_ID, STORE_ID, STORE_NAME
   FROM STORE_INFORMATION S, G
   WHERE S.GEOGRAPHY_ID = G.GEOGRAPHY_ID
)
SELECT S.* FROM S;


WITH G AS (
	SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
),
S AS (
   SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE, GEOGRAPHY_ID
   FROM STORE_INFORMATION S
)
SELECT G.*, S.*
FROM G 
JOIN S ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;





