-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID
FROM employees E
ORDER BY E.DEPARTMENT_ID, E.SALARY DESC;


SELECT DEP_AVG_SALARY.*, E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID
FROM (
	-- 1.查詢每個部門平均薪資
	SELECT E.DEPARTMENT_ID, AVG(E.SALARY) "AVG_DEP"
	FROM employees E
	GROUP BY E.DEPARTMENT_ID
) DEP_AVG_SALARY, employees E
WHERE DEP_AVG_SALARY.XXXX =  E.XXXX 
-- 2.與原先的employees員工做平均薪資比較(大於)
AND E.XXX > DEP_AVG_SALARY.XXX;

