SELECT STORE_NAME FROM store_information;

SELECT STORE_ID, STORE_NAME FROM store_information;

SELECT STORE_ID, SALES, STORE_NAME FROM store_information;

SELECT * FROM store_information;

--  MySQL允許以下查詢(不建議)
SELECT *, STORE_NAME FROM store_information;

-- 商店名稱去重覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 1.DISTINCT 位置必須下在欄位的最前面
-- 2.DISTINCT 只能下一次
-- 3.DISTINCT 是以整列資料為去重覆依據
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

-- 有條件的查詢資料
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION 
WHERE SALES > 1000;


SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION 
WHERE SALES >= 1500;

-- AND且(嚴謹)同時成立
-- OR或(寬鬆)單邊成立
SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION 
WHERE SALES > 250 
AND STORE_DATE > '2018-04-01';


SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE SALES < 300
OR SALES > 2800;


-- 同一個欄位但不同的值做查詢
SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;


SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_ID IN(1,2,3,5);

-- 字串型別的值須用'單引號'
SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME = 'Boston';


SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE
FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Boston', 'Los Angeles');














