CREATE TABLE TABLE1 (
-- 1.值不允許重覆UNIQUE
-- 2.NOT NULL
-- 3.PRIMARY KEY = UNIQUE + NOT NULL
  COLUMN0 CHAR(12) PRIMARY KEY,
-- 不允許一個欄位含有NULL值
	COLUMN1 CHAR(12) NOT NULL,
  COLUMN2 CHAR(12),
-- 1.欄位中的所有資料都是不一樣的值
-- 2.允許NULL
  COLUMN3 CHAR(12) UNIQUE,
--  保證一個欄位中的所有資料都是符合某些條件
  PRICE NUMERIC(10,0) CHECK (PRICE >= 100)
);

-- 組合鍵 (Composite Key)
CREATE TABLE TABLE2  (
  COLUMN1 VARCHAR(20) NOT NULL ,
  COLUMN2 VARCHAR(20) NOT NULL ,
  CONSTRAINT TABLE2_PK PRIMARY KEY  (COLUMN1,COLUMN2)
);

CREATE TABLE TABLE3(
  COLUMN1 VARCHAR(20),
  COLUMN2 VARCHAR(20)
);

-- 以下則是以ALTER改變現有表格架構來設定主鍵的方式：
ALTER TABLE TABLE3 ADD PRIMARY KEY (COLUMN1);


CREATE TABLE GEOGRAPHY (  
	GEOGRAPHY_ID NUMERIC (10,0) PRIMARY KEY,
	REGION_NAME  VARCHAR(255)
);

CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMERIC (10,0) PRIMARY KEY,
	STORE_NAME VARCHAR(255),
	SALES      NUMERIC (10,0) CHECK (SALES > 0),
	STORE_DATE datetime,
-- 	GEOGRAPHY_ID NUMERIC(10,0) REFERENCES GEOGRAPHY(GEOGRAPHY_ID)
 	GEOGRAPHY_ID NUMERIC (10,0),
 	CONSTRAINT CONSTRAINT_GEOGRAPHY_ID FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY (GEOGRAPHY_ID)
);

CREATE VIEW REGION_SUM_SALES_VIEW AS (
	SELECT G.REGION_NAME, IFNULL(SUM(S.SALES), 0) "REGION_SUM_SALES"
	FROM GEOGRAPHY G LEFT JOIN STORE_INFORMATION S
	ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
	GROUP BY G.REGION_NAME
	ORDER BY REGION_SUM_SALES DESC
);

SELECT * FROM REGION_SUM_SALES_VIEW;


