-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

SELECT * 
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, SALARY;



WITH AVG_DEP AS (
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) "DEP_AVG_SALARY"
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
),
DEP_AVG_EMP AS (
	SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.DEPARTMENT_ID, E.SALARY,
		AD.DEP_AVG_SALARY
    FROM AVG_DEP AD, EMPLOYEES E
    -- 1.同部門與同部門薪資比較
    WHERE AD.DEPARTMENT_ID = E.DEPARTMENT_ID
    -- 2.查詢高於部門平均薪資
    AND E.SALARY > AD.DEP_AVG_SALARY
)
SELECT DAE.EMPLOYEE_ID, DAE.FIRST_NAME, DAE.DEPARTMENT_ID, D.DEPARTMENT_NAME, DAE.SALARY,
		DAE.DEP_AVG_SALARY
FROM DEP_AVG_EMP DAE JOIN departments D
ON DAE.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY DEP_AVG_SALARY DESC, SALARY DESC;

