-- HR DB 資料查詢
-- 查詢所有部門資訊如下：
-- 1.所在地(國家、洲省、城市)
-- 2.部門(部門編號、部門名稱)
-- 3.部門管理者(員工編號、員工姓名、員工職稱)

-- Step1:列出「資料表」、「資料欄」
-- LOCATIONS(COUNTRY_ID,STATE_PROVINCE,CITY)
-- DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
-- EMPLOYEES(EMPLOYEE_ID, FIRST_NAME)
-- JOBS(JOB_TITLE)

-- Step2:列出「資料表」與「資料表」之間關聯欄位
-- LOCATIONS(LOCATION_ID)DEPARTMENTS
-- DEPARTMENTS(MANAGER_ID, EMPLOYEE_ID)EMPLOYEES
-- EMPLOYEES(JOB_ID)JOBS

-- Step3:寫SQL

SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
JOIN ... ON ...

