-- SQL 練習題(五)
-- HR DB 資料查詢
-- 查詢所有部門資訊如下：
-- 1.所在地(國家、洲省、城市)
-- 2.部門(部門編號、部門名稱)
-- 3.部門管理者(員工編號、員工姓名、員工職稱)

-- Step1:列出「資料表」、「資料欄」
-- LOCATIONS(COUNTRY_ID,STATE_PROVINCE,CITY)
-- DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
-- EMPLOYEES(EMPLOYEE_ID, FIRST_NAME)
-- JOBS(JOB_TITLE)

-- Step2:列出「資料表」與「資料表」之間關聯欄位
-- LOCATIONS(LOCATION_ID)DEPARTMENTS
-- DEPARTMENTS(MANAGER_ID, EMPLOYEE_ID)EMPLOYEES
-- EMPLOYEES(JOB_ID)JOBS

-- Step3:寫SQL

SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID, E.FIRST_NAME, J.JOB_TITLE
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;


SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    IFNULL(E.EMPLOYEE_ID, 101) "EMP_EMPLOYEE_ID", 
    IFNULL(E.FIRST_NAME, (SELECT FIRST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_EMPLOYEE_ID) ) "FIRST_NAME", 
    IFNULL(J.JOB_TITLE, (SELECT J.JOB_TITLE FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID WHERE E.EMPLOYEE_ID = EMP_EMPLOYEE_ID) ) "JOB_TITLE"
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;


-- 計算各部門人數(107)
-- ps:包含沒有部門的員工
SELECT IFNULL(D.DEPARTMENT_ID, '00'), IFNULL(D.DEPARTMENT_NAME, 'NON_DEP'), 
	COUNT(E.EMPLOYEE_ID) "DEP_EMP_COUNT"
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY DEP_EMP_COUNT DESC, D.DEPARTMENT_ID DESC;


-- 各部門的平均薪資
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, FLOOR(AVG(E.SALARY)) "DEP_AVG_SALARY"
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY DEP_AVG_SALARY DESC;


-- 計算每個員工職務與最高、最低與個人薪資差異數字
-- EMPLOYEES(JOB_ID)JOBS
-- EMPLOYEE_ID,FIRST_NAME, JOB_ID,JOB_TITLE, SALARY(MIN_SALARY), SALARY(MAX_SALARY)
SELECT E.DEPARTMENT_ID, E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY,
	E.SALARY - J.MIN_SALARY "RANGE_MIN_SALARY", J.MAX_SALARY - E.SALARY "RANGE_MAX_SALARY",
	J.JOB_ID, J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
ORDER BY E.DEPARTMENT_ID;

-- 每個地區regions的員工數量(107位)
-- REGIONS(REGION_ID)COUNTRIES
-- COUNTRIES(COUNTRY_ID)LOCATIONS
-- LOCATIONS(LOCATION_ID)DEPARTMENTS
-- DEPARTMENTS(DEPARTMENT_ID)EMPLOYEES
SELECT IFNULL(R.REGION_ID, 0) "REGION_ID", R.REGION_NAME, COUNT(E.EMPLOYEE_ID) "REGION_EMP_COUNT"
FROM REGIONS R
JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
LEFT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY R.REGION_ID, R.REGION_NAME
ORDER BY REGION_EMP_COUNT DESC;


-- FULL JOIN = LEFT JOIN + RIGHT JOIN
SELECT IFNULL(R.REGION_ID, 0) "REGION_ID", R.REGION_NAME, COUNT(E.EMPLOYEE_ID) "REGION_EMP_COUNT"
FROM REGIONS R
JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
LEFT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY R.REGION_ID, R.REGION_NAME
UNION
SELECT IFNULL(R.REGION_ID, 0) "REGION_ID", R.REGION_NAME, COUNT(E.EMPLOYEE_ID) "REGION_EMP_COUNT"
FROM REGIONS R
JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
LEFT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
RIGHT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY R.REGION_ID, R.REGION_NAME;
