-- SQL 練習題(五)
-- HR DB 資料查詢
-- 查詢所有部門資訊如下：
-- 1.所在地(國家、洲省、城市)
-- 2.部門(部門編號、部門名稱)
-- 3.部門管理者(員工編號、員工姓名、員工職稱)

-- Step1:列出「資料表」、「資料欄」
-- LOCATIONS(COUNTRY_ID,STATE_PROVINCE,CITY)
-- DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
-- EMPLOYEES(EMPLOYEE_ID, FIRST_NAME)
-- JOBS(JOB_TITLE)

-- Step2:列出「資料表」與「資料表」之間關聯欄位
-- LOCATIONS(LOCATION_ID)DEPARTMENTS
-- DEPARTMENTS(MANAGER_ID, EMPLOYEE_ID)EMPLOYEES
-- EMPLOYEES(JOB_ID)JOBS

-- Step3:寫SQL

SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID, E.FIRST_NAME, J.JOB_TITLE
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;


SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY,
	D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
    IFNULL(E.EMPLOYEE_ID, 101) "EMP_EMPLOYEE_ID", 
    IFNULL(E.FIRST_NAME, (SELECT FIRST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_EMPLOYEE_ID) ) "FIRST_NAME", 
    IFNULL(J.JOB_TITLE, (SELECT J.JOB_TITLE FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID WHERE E.EMPLOYEE_ID = EMP_EMPLOYEE_ID) ) "JOB_TITLE"
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;

-- 計算各部門人數
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;