SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, SALES, STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT:資料去重覆
-- 以整列為判斷依據
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;


SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或(寬鬆)
SELECT * 
FROM STORE_INFORMATION
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME = 'Los Angeles';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;


SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01' AND '2018-05-30';

SELECT * 
FROM STORE_INFORMATION
WHERE STR_TO_DATE(STORE_DATE , "%Y-%m")
BETWEEN STR_TO_DATE('2018-03', "%Y-%m") AND STR_TO_DATE('2018-05', "%Y-%m");

-- 字串轉日期
-- STR_TO_DATE(str,format)
SELECT STR_TO_DATE('2021-08-15 00:00:00', "%Y-%m-%d %T");




