SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, SALES, STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT:資料去重覆
-- 以整列為判斷依據
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;


SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或(寬鬆)
SELECT * 
FROM STORE_INFORMATION
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME = 'Los Angeles';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;


SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01' AND '2018-05-30';

SELECT STORE_ID, STORE_NAME, STORE_DATE, STR_TO_DATE(STORE_DATE , "%Y-%m") 
FROM STORE_INFORMATION
WHERE STR_TO_DATE(STORE_DATE , "%Y-%m")
BETWEEN STR_TO_DATE('2018-03', "%Y-%m") AND STR_TO_DATE('2018-05', "%Y-%m");

-- 字串轉日期
-- STR_TO_DATE(str,format)
SELECT STR_TO_DATE('2021-08-15 00:00:00', "%Y-%m-%d %T");


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%An%';


-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱“L”開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2
AND SALES >= 300
AND STORE_NAME LIKE 'L%'
OR STR_TO_DATE(STORE_DATE , "%Y-%m")
BETWEEN STR_TO_DATE('2018-03', "%Y-%m") AND STR_TO_DATE('2018-04', "%Y-%m");

-- 小往大 (ascending) ASC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES ASC;

-- 大往小(descending) DESC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES DESC;

-- 預設：小往大 (ascending) ASC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES;


-- 主排序(營業額)、次排序(營業日)
SELECT *
FROM STORE_INFORMATION
ORDER BY SALES DESC, STORE_DATE DESC;


-- SQL Aggregate Functions 聚合函數
SELECT SUM(SALES), COUNT(STORE_ID), AVG(SALES),
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION;


SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NULL;


SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NOT NULL;

-- 以商店名稱"去重覆"的"資料筆數"
SELECT COUNT(DISTINCT STORE_NAME) FROM STORE_INFORMATION;


-- 個別商店加總營業額
-- 資料分群、資料合併
-- 其它"非群組欄位"須指定"聚合函數"
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID), AVG(SALES),
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 資料分群可下多個欄位
SELECT STORE_ID, STORE_NAME
FROM STORE_INFORMATION
GROUP BY STORE_ID, STORE_NAME;

-- MySQL
-- 群組資料清單
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
	GROUP_CONCAT(SALES ORDER BY SALES SEPARATOR '/')
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- Oracle
-- 群組資料清單
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
  LISTAGG(SALES, '/') WITHIN GROUP (ORDER BY SALES)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;


-- MS SQL
-- 群組資料清單
SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
	    STRING_AGG(SALES, '/') WITHIN GROUP (ORDER BY SALES DESC)
FROM STORE_INFORMATION
GROUP BY STORE_NAME;


-- SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY
SELECT STORE_NAME, SUM(SALES)
FROM STORE_INFORMATION
-- WHERE SUM(SALES) >= 3000
GROUP BY STORE_NAME
HAVING SUM(SALES) >= 3000
ORDER BY SUM(SALES) DESC;


-- 計算和統計「個別商店」的以下三項資料：
-- 「總合營業額」、「商店資料個數」、「平均營業額」
-- 搜尋或排除條件如下：
-- 排除「平均營業額」1000(含)以下的商店資料
-- 排除「商店資料個數」1(含)個以下的商店資料
-- 依照「平均營業額」由大至小排序
-- PS:使用別名語法簡化「表格名稱」及查詢結果「欄位名稱」

