SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, SALES, STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- DISTINCT:資料去重覆
-- 以整列為判斷依據
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;


SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或(寬鬆)
SELECT * 
FROM STORE_INFORMATION
WHERE SALES > 1000
OR (SALES > 275 AND SALES < 500);


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME = 'Los Angeles';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;


SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-03-01' AND '2018-05-30';

SELECT STORE_ID, STORE_NAME, STORE_DATE, STR_TO_DATE(STORE_DATE , "%Y-%m") 
FROM STORE_INFORMATION
WHERE STR_TO_DATE(STORE_DATE , "%Y-%m")
BETWEEN STR_TO_DATE('2018-03', "%Y-%m") AND STR_TO_DATE('2018-05', "%Y-%m");

-- 字串轉日期
-- STR_TO_DATE(str,format)
SELECT STR_TO_DATE('2021-08-15 00:00:00', "%Y-%m-%d %T");


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'B%';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%s';

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE 'L%s';


SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME LIKE '%An%';


-- 1.「且」找出屬於西區的商店
-- 2.「且」營業額大於300(包含300)
-- 3.「且」商店名稱“L”開頭
-- 4.「或」營業日介於2018年3月至4月
SELECT * FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID = 2
AND SALES >= 300
AND STORE_NAME LIKE 'L%'
OR STR_TO_DATE(STORE_DATE , "%Y-%m")
BETWEEN STR_TO_DATE('2018-03', "%Y-%m") AND STR_TO_DATE('2018-04', "%Y-%m");

-- 小往大 (ascending) ASC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES ASC;

-- 大往小(descending) DESC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES DESC;

-- 預設：小往大 (ascending) ASC
SELECT * FROM STORE_INFORMATION
ORDER BY SALES;


-- 主排序(營業額)、次排序(營業日)
SELECT *
FROM STORE_INFORMATION
ORDER BY SALES DESC, STORE_DATE DESC;


-- SQL Aggregate Functions 聚合函數
SELECT SUM(SALES), COUNT(STORE_ID), AVG(SALES),
	MAX(SALES), MIN(SALES)
FROM STORE_INFORMATION;


SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NULL;


SELECT COUNT(STORE_ID)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IS NOT NULL;





