-- Alias (別名) 
-- 欄位別名
-- AS "雙引號"
-- 1.AS 可省略不寫
-- 2."雙引號"可省略不寫(別名中間不能有空白)
SELECT STORE_NAME "商業名稱", SUM(SALES) 營業額, COUNT(STORE_ID) "數量",
	GROUP_CONCAT(SALES ORDER BY SALES SEPARATOR '/') AS "GROUP SALES LIST"
FROM STORE_INFORMATION
GROUP BY STORE_NAME;

-- 表格別名
SELECT S.STORE_ID, S.STORE_NAME
FROM STORE_INFORMATION S;


SELECT * FROM GEOGRAPHY;
SELECT * FROM STORE_INFORMATION;

-- JOIN 跨資料表關聯查詢
SELECT G.*, S.* 
FROM GEOGRAPHY G, STORE_INFORMATION S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- INNER JOIN ... ON
-- INNER 可省略不寫
SELECT G.*, S.* 
FROM GEOGRAPHY G INNER JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

SELECT G.*, S.* 
FROM GEOGRAPHY G JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


-- LEFT OUTER JOIN ... ON
-- OUTER 可省略不寫
SELECT G.*, S.* 
FROM GEOGRAPHY G LEFT OUTER JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.*, S.* 
FROM GEOGRAPHY G LEFT JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;





