DROP TABLE STORE_INFORMATION;
DROP TABLE GEOGRAPHY;

CREATE TABLE GEOGRAPHY (  
	GEOGRAPHY_ID NUMBER(10,0) PRIMARY KEY,
	REGION_NAME  VARCHAR2(255)
);

COMMENT ON COLUMN GEOGRAPHY.GEOGRAPHY_ID IS '地區編號';
COMMENT ON COLUMN GEOGRAPHY.REGION_NAME IS '地區名稱';


CREATE TABLE STORE_INFORMATION(
	STORE_ID   NUMBER(10,0) PRIMARY KEY,
	STORE_NAME VARCHAR2(255),
	SALES      NUMBER(10,0) CHECK (SALES > 0),
	STORE_DATE TIMESTAMP (6),
	-- GEOGRAPHY_ID NUMBER(10,0) REFERENCES GEOGRAPHY(GEOGRAPHY_ID)
	GEOGRAPHY_ID NUMBER(10,0),
	CONSTRAINT CONSTRAINT_GEOGRAPHY_ID FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY (GEOGRAPHY_ID)
);

COMMENT ON COLUMN STORE_INFORMATION.STORE_ID IS '商店編號';
COMMENT ON COLUMN STORE_INFORMATION.STORE_NAME IS '商店名稱';
COMMENT ON COLUMN STORE_INFORMATION.SALES IS '營業額';
COMMENT ON COLUMN STORE_INFORMATION.STORE_DATE IS '開始營業日';
COMMENT ON COLUMN STORE_INFORMATION.GEOGRAPHY_ID IS '地區編號';
