DROP TABLE PLAYERS;
CREATE TABLE PLAYERS(
 PLAYER_ID INT,
 GROUP_ID INT,
 PRIMARY KEY (PLAYER_ID)
);

DROP TABLE MATCHES;
CREATE TABLE MATCHES(
 MATCH_ID INT,
 FIRST_PLAYER INT,
 SECOND_PLAYER INT,
 FIRST_SCORE INT,
 SECOND_SCORE INT,
 PRIMARY KEY (MATCH_ID)
);
INSERT INTO PLAYERS VALUES (15, 1);
INSERT INTO PLAYERS VALUES (25, 1);
INSERT INTO PLAYERS VALUES (30, 1);
INSERT INTO PLAYERS VALUES (45, 1);
INSERT INTO PLAYERS VALUES (10, 2);
INSERT INTO PLAYERS VALUES (35, 2);
INSERT INTO PLAYERS VALUES (50, 2);
INSERT INTO PLAYERS VALUES (20, 3);
INSERT INTO PLAYERS VALUES (40, 3);
INSERT INTO MATCHES VALUES (1,15,45,3,0);
INSERT INTO MATCHES VALUES (2,30,25,1,2);
INSERT INTO MATCHES VALUES (3,30,15,2,0);
INSERT INTO MATCHES VALUES (4,40,20,5,2);
INSERT INTO MATCHES VALUES (5,35,50,1,1);
COMMIT;