DROP TABLE NUMBERS;
CREATE TABLE NUMBERS ("NUMBER" INT, FREQUENCY INT);
INSERT INTO NUMBERS ("NUMBER", FREQUENCY) VALUES ('0', '7');
INSERT INTO NUMBERS ("NUMBER", FREQUENCY) VALUES ('1', '1');
INSERT INTO NUMBERS ("NUMBER", FREQUENCY) VALUES ('2', '3');
INSERT INTO NUMBERS ("NUMBER", FREQUENCY) VALUES ('3', '1');
COMMIT;